POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username":"arash",
    "email":"arash@yahoo.com",
    "password":"123456",


}

###
POST http://localhost:5000/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "username":"arshia",
    "email":"arshia@yahoo.com",
    "password":"654321",  
    "isAdmin":true
}
###
POST http://localhost:5000/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"arshia@yahoo.com",
    "password":"123456"
}

###
POST http://localhost:5000/api/products/create
Content-Type: application/json
auth-token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjVmOTg4ZTkyZjBiNDhkMTljMGQwMTZhZiIsInVzZXJuYW1lIjoiYXJhc2giLCJlbWFpbCI6ImFyYXNoQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFIwcGswbUN6Z2FGV3BZNktHMTlBY3VBQ0dwTTFaSncyTHVYY203WDZQVDJ4RC9RL0hPNVcuIiwiX192IjowfSwiaWF0IjoxNjAzODMzNDkxLCJleHAiOjE2MDQxOTM0OTF9.bXEDcUSR0DJfF7pBxW74mUnVtTimZ9SKrb_1tLX08Wc

{
    "name":"x",
    "price":123,
    "category":"ff",
    "color":["d","d"],
    "size":["x","s"],
    "description":"dadada",
    "countInStock":2,
    "image":"dada"

}


###
DELETE  http://localhost:5000/api/products/5f989003108aa9177481f64b/delete
Content-Type: application/json
auth-token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjVmOTg4ZTkyZjBiNDhkMTljMGQwMTZhZiIsInVzZXJuYW1lIjoiYXJhc2giLCJlbWFpbCI6ImFyYXNoQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFIwcGswbUN6Z2FGV3BZNktHMTlBY3VBQ0dwTTFaSncyTHVYY203WDZQVDJ4RC9RL0hPNVcuIiwiX192IjowfSwiaWF0IjoxNjAzODMzNDkxLCJleHAiOjE2MDQxOTM0OTF9.bXEDcUSR0DJfF7pBxW74mUnVtTimZ9SKrb_1tLX08Wc

###
PUT  http://localhost:5000/api/products/5f988ee36a2ffb1a5c6379ac/update
Content-Type: application/json
auth-token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjVmOTg4ZTkyZjBiNDhkMTljMGQwMTZhZiIsInVzZXJuYW1lIjoiYXJhc2giLCJlbWFpbCI6ImFyYXNoQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFIwcGswbUN6Z2FGV3BZNktHMTlBY3VBQ0dwTTFaSncyTHVYY203WDZQVDJ4RC9RL0hPNVcuIiwiX192IjowfSwiaWF0IjoxNjAzODMzNDkxLCJleHAiOjE2MDQxOTM0OTF9.bXEDcUSR0DJfF7pBxW74mUnVtTimZ9SKrb_1tLX08Wc

{
    "name":"first1",
    "price":123,
    "category":"ff",
    "color":["d","d"],
    "size":["x","s"],
    "description":"dadada",
    "countInStock":2,
    "image":"dada"

}

###
GET http://localhost:5000/api/products/f

###
GET  http://localhost:5000/api/users
Content-Type: application/json
auth-token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjVmOTg4ZTkyZjBiNDhkMTljMGQwMTZhZiIsInVzZXJuYW1lIjoiYXJhc2giLCJlbWFpbCI6ImFyYXNoQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFIwcGswbUN6Z2FGV3BZNktHMTlBY3VBQ0dwTTFaSncyTHVYY203WDZQVDJ4RC9RL0hPNVcuIiwiX192IjowfSwiaWF0IjoxNjAzODMzNDkxLCJleHAiOjE2MDQxOTM0OTF9.bXEDcUSR0DJfF7pBxW74mUnVtTimZ9SKrb_1tLX08Wc

###
PUT  http://localhost:5000/api/users/5f98a6ca5b50530eec3402bf
Content-Type: application/json
auth-token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjVmOTg4ZTkyZjBiNDhkMTljMGQwMTZhZiIsInVzZXJuYW1lIjoiYXJhc2giLCJlbWFpbCI6ImFyYXNoQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFIwcGswbUN6Z2FGV3BZNktHMTlBY3VBQ0dwTTFaSncyTHVYY203WDZQVDJ4RC9RL0hPNVcuIiwiX192IjowfSwiaWF0IjoxNjAzODMzNDkxLCJleHAiOjE2MDQxOTM0OTF9.bXEDcUSR0DJfF7pBxW74mUnVtTimZ9SKrb_1tLX08Wc

{
    "username":"ali",
    "email":"ali@yahoo.com",
    "password":"123456"
}

###
DELETE  http://localhost:5000/api/users/5f98a6ca5b50530eec3402bf
Content-Type: application/json
auth-token :eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlzQWRtaW4iOnRydWUsIl9pZCI6IjVmOTg4ZTkyZjBiNDhkMTljMGQwMTZhZiIsInVzZXJuYW1lIjoiYXJhc2giLCJlbWFpbCI6ImFyYXNoQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJFIwcGswbUN6Z2FGV3BZNktHMTlBY3VBQ0dwTTFaSncyTHVYY203WDZQVDJ4RC9RL0hPNVcuIiwiX192IjowfSwiaWF0IjoxNjAzODMzNDkxLCJleHAiOjE2MDQxOTM0OTF9.bXEDcUSR0DJfF7pBxW74mUnVtTimZ9SKrb_1tLX08Wc



